Repository wanted-FE-team1/pre-onboarding-11th-1-1, pull requests merged in 2023-06, with the labels that each got.

#2 [Feature/#1] PR, ISSUE 템플릿 작성
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/hotfix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ✨ feature

#3 [Feature/#2] Project Setting
  .eslintrc
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/hotfix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  .prettierrc.js
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.tsx
  src/components/common/Form.tsx
  src/components/join/JoinInput.tsx
  src/components/login/LoginInput.tsx
  src/components/todo/TodoInput.tsx
  src/index.css
  src/index.tsx
  src/pages/ErrorPage.tsx
  src/pages/JoinPage.tsx
  src/pages/LoadingPage.tsx
  src/pages/LoginPage.tsx
  src/pages/TodoPage.tsx
  src/react-app-env.d.ts
  src/routers/Router.tsx
  src/types/common.ts
  src/utils/Api.ts
  src/utils/Localstorage.ts
  tailwind.config.js
  tsconfig.json
Labels: ✨ feature

#11 [Feature/#9] Localstorage get, set, remove 함수 추가
  package-lock.json
  src/utils/Localstorage.ts
Labels: ✨ feature

#7 [Feature/#4] api함수 모듈화
  package-lock.json
  package.json
  src/utils/Api.ts
  tsconfig.json
Labels: ✨ feature

#12 [Feature/#10] loading,error페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/pages/ErrorPage.tsx
  src/pages/LoadingPage.tsx
  src/utils/api.ts
  src/utils/localStorage.ts
Labels: ✨ feature

#16 [Feture/#7] 라우터 구현
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/App.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/index.tsx
  src/pages/NotFoundPage.tsx
  src/routers/Root.tsx
  src/routers/Router.tsx
  src/routers/redirect.ts
Labels: ✨ feature

#14 [Feature/#6] 로그인 페이지 구현
  package.json
  src/components/common/AuthForm.tsx
  src/components/common/AuthInput.tsx
  src/components/common/Form.tsx
  src/components/join/JoinInput.tsx
  src/components/login/LoginInput.tsx
  src/pages/JoinPage.tsx
  src/pages/LoginPage.tsx
  src/types/common.ts
  src/utils/sign.ts
Labels: ✨ feature

#13 [Feature/#5] 투두 페이지 구현
  package-lock.json
  src/App.tsx
  src/components/todo/AddTodo.tsx
  src/components/todo/TodoInput.tsx
  src/components/todo/TodoItem.tsx
  src/hooks/useTodo.ts
  src/pages/TodoPage.tsx
  src/types/common.ts
  src/utils/api.ts
  src/utils/constants.ts
Labels: ✨ feature

#19 [Docs/readme] README.md 문서 작성
  README.md
Labels: documentation

#20 [Feature/#18] 변수, 함수명 통일
  package-lock.json
  src/App.tsx
  src/components/common/AuthForm.tsx
  src/components/common/AuthInput.tsx
  src/components/common/Header.tsx
  src/components/todo/TodoItem.tsx
  src/pages/JoinPage.tsx
  src/pages/LoginPage.tsx
  src/types/common.ts
  src/utils/api.ts
  src/utils/constants.ts
  src/utils/localStorage.ts
  src/utils/validation.ts
Labels: ♻️ refactor

#22 [Feature/#21] 로그인, 회원가입 페이지 경로명 변경
  src/components/common/Header.tsx
  src/pages/JoinPage.tsx
  src/pages/LoginPage.tsx
  src/routers/Router.tsx
  src/routers/redirect.ts
  src/utils/constants.ts
Labels: 🐛 fix
